# Generated by Django 4.2.1 on 2023-07-07 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movieactor_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElasticSearchMovie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                            ("EXPIRED", "Expired"),
                            ("FORWARDED", "Forwarded"),
                        ],
                        default="READY",
                        max_length=50,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Elasticsearch Movie",
                "verbose_name_plural": "Elasticsearch Movies",
                "db_table": "elasticsearch_movie",
                "ordering": ["-created", "-updated"],
                "indexes": [
                    models.Index(fields=["status"], name="EM_status_idx"),
                    models.Index(fields=["created"], name="EM_created_idx"),
                    models.Index(
                        fields=["created", "status"], name="EM_created_status_idx"
                    ),
                ],
            },
        ),
    ]
